name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          coverage: xdebug
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --no-suggest --prefer-dist --optimize-autoloader
        env:
          APP_ENV: testing

      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing
          DB_DATABASE: test
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - uses: codecov/codecov-action@v1
        with:
          file: ./build/logs/clover.xml
          flags: unittests
          fail_ci_if_error: true
